version: 2

executors:
  node:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.14
  python:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.7

jobs:
  node-modules-install:
    executor: node
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      #
      - persist_to_workspace:
          root: ./
          paths:
            - abis
            - fork
            - migrations
            - .openzeppelin
            - test
            - contracts
            - utils
            - Pipfile
            - .solcover.js
            - package.json
            - .nvmrc
            - scripts
            - truffle-config.js
            - .oz-migrate
            - erc20.json
            - Pipfile.lock
            - node_modules

  test:
    docker:
      - image: circleci/node:8.14

    steps:
      # Run Coverage Report
      - run: mkdir ~/junit
      - run:
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          command: MOCHA_FILE=~/junit/test-results.xml yarn coverage
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  verify:
    docker:
      - image: circleci/python:3.7.7

    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache: # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"

      # Verify Contracts
      - run: pipenv run mythx -y --api-key $MYTHX_API_KEY analyze contracts/*

workflows:
  version: 2
  test_and_verify:
    jobs:
      # - test:
      #     requires:
      #       - node-modules-install

      - verify:
          requires:
            - node-modules-install
